Introduce before and after steps for a task.
tj/robo pull request #56
Opened 2022-06-09 20:57 UTC by jenpet

Hey guys, I fiddled around with some `before` and `after` functionality I could use within robo. Hopefully this finds a way into master. Let me know what you think :-)

A task is now able to have several steps which are executed before and after its own execution. The config syntax for this is the same as for the task itself: 'command', 'script' and 'exec' are supported. A task and all of the preceeding steps will still be executed even when the before steps are failing.

Running a task now returns a list of errors which are logged according to their occurrence for easier troubleshooting.

2022-06-13 14:51 UTC, jenpet commented
@yields *ping* 😊

2022-06-13 18:19 UTC, yields requested changes
LGTM, seems like it just needs some docs to match the rest of the codebase.

2022-06-13 18:19 UTC, yields commented on interpolation/interpolation.go
> +func Optionals(id string, rs []*task.Runnable, data map[string]interface{}) error {
Can we add docs to this one? 🙏 Just to match the rest of the codebase.

2022-06-13 18:19 UTC, yields commented on task/task.go
> +type Runnable struct {
ditto

2022-06-13 18:19 UTC, yields commented on task/task.go
> +func (r *Runnable) Run(lookupPath string, args []string, env []string) error {
ditto

2022-06-13 18:19 UTC, yields commented on task/task.go
> +func RunOptionals(id string, parent string, rs []*Runnable, args []string, lookupPath string, envs []string) error {
ditto

2022-06-19 12:26 UTC, jenpet commented
@yields updated the code documentation and the readme accordingly. If you are happy with it, I will squash the commits into a single reasonable commit.

2022-06-20 09:52 UTC, yields approved these changes
Awesome! -- thanks for the extra docs :)

2022-06-20 09:52 UTC, merged